# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1seknmKmOX_VkoOFauyQ2zfmVIDmwRdFQ
"""

import numpy as np
from numpy.linalg import inv

# Initialize empty matrix
matrix = []
print("Enter the entries row wise:")

for i in range(2):
   # empty row
   row = []
   for j in range(2):
      # asking the user to input the number
      # converts the input to int as the default one is string
      element = int(input())
      # appending the element to the 'row'
      row.append(element)
   # appending the 'row' to the 'matrix'
   matrix.append(row)
# printing the matrix
#print(matrix)

#Find Inverse

a = np.array(matrix)
print(a, '\n')

ainv = inv(a)
ainv = ainv.round(2)

print(ainv)